<?php

namespace Tests\Functional\Helper\Asset;

use App\Company;
use App\Helper\Asset\Thumbnail;
use App\Stock;
use Tests\TestCase;

use Illuminate\Foundation\Testing\DatabaseTransactions;

/**
 * Class CompanyTest
 * @package Tests\Unit
 */
class ThumbnailTest extends TestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }


    public function testGetPagenameByUrl()
    {
        $url = "http://172.17.0.1:8181/export/293665700abaaf23d2345c1b1ddd3fad/document.exportjpg_91.jpg";

        $pageName = Thumbnail::getPagenameByUrl($url);

        $this->assertEquals(91, $pageName);
    }
}
